version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    ports:
      - "8080:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: