version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    ports:
      - "8080:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    build: .
    container_name: pixel-art-app
    ports:
      - "9500:9500"
      - "3000:3000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
volumes:
  pgdata: